In [57]:
import pandas as pd

In [58]:
res=pd.read_csv('./comga.csv')

In [59]:
res[res['dataset']=='ACM'].sort_values('auc',ascending=False)

,dataset,seed,num_nodes,num_feats,n_enc_1,n_enc_2,n_enc_3,dropout,lr,logdir,num_epoch,alpha,eta,theta,device,auc,attribute_auc,structure_auc
3029,ACM,1,16484,8337,2000,500,128,0.2,0.00001,log/ACM_ComGA1,400,0.01,1.0,10.0,0,0.714702,-1.0,0.714702
3034,ACM,1,16484,8337,2000,500,128,0.2,0.00001,log/ACM_ComGA1,400,0.01,3.0,10.0,0,0.714675,-1.0,0.714675
3039,ACM,1,16484,8337,2000,500,128,0.2,0.00001,log/ACM_ComGA1,400,0.01,5.0,10.0,0,0.714627,-1.0,0.714627
3044,ACM,1,16484,8337,2000,500,128,0.2,0.00001,log/ACM_ComGA1,400,0.01,7.0,10.0,0,0.714595,-1.0,0.714595
3049,ACM,1,16484,8337,2000,500,128,0.2,0.00001,log/ACM_ComGA1,400,0.01,10.0,10.0,0,0.714529,-1.0,0.714529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1758,ACM,1,16484,8337,2000,500,128,0.2,0.00100,log/ACM_ComGA1,300,0.40,1.0,90.0,0,0.210422,-1.0,0.210422
1458,ACM,1,16484,8337,2000,500,128,0.2,0.00100,log/ACM_ComGA1,100,0.40,1.0,90.0,0,0.210414,-1.0,0.210414
2058,ACM,1,16484,8337,2000,500,128,0.2,0.00010,log/ACM_ComGA1,100,0.40,1.0,90.0,0,0.209708,-1.0,0.209708
2208,ACM,1,16484,8337,2000,500,128,0.2,0.00010,log/ACM_ComGA1,200,0.40,1.0,90.0,0,0.209669,-1.0,0.209669
2358,ACM,1,16484,8337,2000,500,128,0.2,0.00010,log/ACM_ComGA1,300,0.40,1.0,90.0,0,0.209607,-1.0,0.209607

In [60]:
def get_top(x):
    x=x.sort_values('auc',ascending=False)
    return x.iloc[0]

In [61]:
drop_feas = ['logdir','device']
use_cols = [i for i in res.columns.values if i not in drop_feas]

In [62]:
res.groupby('dataset',as_index=False).apply(get_top)[use_cols]

,dataset,seed,num_nodes,num_feats,n_enc_1,n_enc_2,n_enc_3,dropout,lr,num_epoch,alpha,eta,theta,auc,attribute_auc,structure_auc
0,ACM,1,16484,8337,2000,500,128,0.2,0.00001,400,0.01,1.0,10.0,0.714702,-1.000000,0.714702
1,BlogCatalog,1,5196,8189,2000,500,128,0.2,0.00100,100,0.01,10.0,10.0,0.790767,0.965312,0.616223
2,Citeseer,1,3327,3703,2000,500,128,0.2,0.00100,100,0.01,1.0,10.0,0.801979,0.611203,0.992754
3,Cora,1,2708,1433,2000,500,128,0.2,0.00100,100,0.80,7.0,10.0,0.967667,0.964613,0.970722
4,Flickr,4096,7575,12047,2000,500,128,0.0,0.00001,100,0.40,8.0,90.0,0.734625,0.979687,0.489563
5,Pubmed,1,19717,500,2000,500,128,0.2,0.00100,400,0.80,10.0,10.0,0.920485,0.908469,0.932500